language: java
jdk:
  - openjdk12
sudo: false
script: sh scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1ece7af6-46e4-4b36-aba9-58417841b1c4
env:
  global:
    - CODECOV_TOKEN=:1ece7af6-46e4-4b36-aba9-58417841b1c4